### ISSUE TITLE
URL duplicado

### ISSUE THREAD

**Issue by iuriguilherme** [pedromoraes/naofo.de#7]
Encurtei por descuido duas vezes o mesmo URL e o sistema não corrigiu isto.

http://naofo.de/2vhi
http://naofo.de/2vhn

O sistema também não detecta automaticamente o título da página mas isto é culpa do webmaster daquele site.

**Comment by pedromoraes** [comment]
Na verdade, corrigiu - ele reaproveita as imagens, mas não impede urls repetidos com o mesmo destino. Isso porque o campo de texto - que pode ter comentários - pode ter valores diferentes
