### ISSUE TITLE
Incluir suporte de tags para o Facebook

### ISSUE THREAD

**Issue by msilvalopes** [pedromoraes/naofo.de#9]
https://developers.facebook.com/docs/sharing/best-practices#tags
Exemplo de sharing:
![captura de tela 2015-05-29 13 44 15](https://cloud.githubusercontent.com/assets/715579/7888786/0400fe66-0609-11e5-9a0a-36c07d7a9fa0.png)
![captura de tela 2015-05-29 13 44 30](https://cloud.githubusercontent.com/assets/715579/7888787/0401230a-0609-11e5-8622-3b30b6a58722.png)

**Comment by msilvalopes** [comment]
URL das fontes, respectivamente:

http://naofo.de/4pq6
e
http://www.infomoney.com.br/mercados/politica/noticia/4072867/como-pensa-joao-rodrigues-deputado-que-assistiu-pornografia-plenario-camara

**Comment by pedromoraes** [comment]
Gozado, já tem suporte -->

![captura de tela 2015-05-29 as 15 06 22](https://cloud.githubusercontent.com/assets/132420/7889209/7cc545a4-0614-11e5-85a3-0a3324bf5ae3.png)

Pode fazer um outro teste?
